[project]
name = "ch2-context-propagation"
version = "0.1.0"
description = "Context Propagation in Python Asyncio"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "fastapi>=0.111.0",
    "uvicorn>=0.30.0",
    "python-dotenv>=1.2.1",
]
